# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed2e559f55a2e31974eae72a01754bbd5ae4f06bd02e279764b38534a3586053a9131553547fdd2bf6247b6aced6ae54cf70bae9705a4f880e68f706c3fd8cda

test:
  secret_key_base: aeec84bee80ff6d5ff16cf18a650d631474b0a5c5fcd3bc68850d0024fcd8a6c3b3a498be5f86792d85c84cbbc29f70137b2c077e351322f3b8e857ef6ade3cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
